### ISSUE TITLE
Implement `Debug` for `Keys` and `Values`

### ISSUE THREAD

**Issue by piegamesde** [rust-phf/rust-phf#192]
I'd like to print only the set of keys when the one I requested is not contained in the map.

**Comment by JohnTitor** [comment]
Hm, we implement `Debug` for map or set's entries already, isn't it enough?

**Comment by piegamesde** [comment]
No, it is not. A `Set` is not the same thing as a `Keys`, and it is not trivial to go from the one to the other.
