### ISSUE TITLE
The removal of Slice breaks rust-postgres

### ISSUE THREAD

**Issue by sfackler** [rust-phf/rust-phf#229]
https://github.com/sfackler/rust-postgres/issues/817

**Comment by JohnTitor** [comment]
Oh sorry, I thought it was safe but actually not. I'll yank the version and published it as 0.10.

**Comment by sfackler** [comment]
Thanks!

**Comment by JohnTitor** [comment]
Okay, yanked the previous version and published v0.10.0. Thanks for reporting!
