### ISSUE TITLE
docs? examples?

### ISSUE THREAD

**Issue by adsick** [rust-phf/rust-phf#231]
Hello, guys, I'm trying to understand how to use the crate, but unfortunately this task does not meant to be accomplish-able(

**Comment by bhgomes** [comment]
This crate is for generating efficient maps and sets at compile-time (i.e. static/const objects).

Here's an example from the [`docs.rs` page](https://docs.rs/phf/0.10.0/phf/):

```rust
use phf::{phf_map, phf_set};

static MY_MAP: phf::Map<&'static str, u32> = phf_map! {
    "hello" => 1,
    "world" => 2,
};

static MY_SET: phf::Set<&'static str> = phf_set! {
    "hello world",
    "hola mundo",
};

fn main() {
    assert_eq!(MY_MAP["hello"], 1);
    assert!(MY_SET.contains("hello world"));
}
```

There are also a few examples in the [`README.md`](https://github.com/rust-phf/rust-phf/blob/master/README.md). 

Is there anything specific that is unclear?
