### ISSUE TITLE
When iterating, the key/value pair exists, but when using `get(&key)`, I get `None`

### ISSUE THREAD

**Issue by alexschrod** [rust-phf/rust-phf#254]
I have this `phf-codegen` created map, where this code:
```rust
#[test]
fn foo() {
    let mut found = false;
    for (key, value) in &MAP {
        if key == &5103 && value == &167 {
            found = true;
            dbg!(key, value);
        }
    }
    assert!(found);
    
    dbg!(MAP.keys().any(|k| k == &5103));
    dbg!(MAP.get_entry(&5103));
    assert_eq!(MAP.get(&5103), Some(&167));
}
```
has the following output:
```
running 1 test
test foo ... FAILED

failures:

---- foo stdout ----
[src/lib.rs:7] key = 5103
[src/lib.rs:7] value = 167
[src/lib.rs:12] MAP.keys().any(|k| k == &5103) = true
[src/lib.rs:13] MAP.get_entry(&5103) = None
thread 'foo' panicked at 'assertion failed: `(left == right)`
  left: `None`,
 right: `Some(167)`', src/lib.rs:14:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    foo

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

I feel like I'm getting some mixed signals here. When iterating, the key `5103` is definitely there, but when trying to access directly with `get` or `get_entry`, there's seemingly no entry for `5103`. Am I doing something wrong here or misunderstanding how a `phf::Map` is supposed to work? Or is there a bug in `phf`?

Test and map code here: <https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=08c6c6ef98b6589d1b27612871c06341>

**Comment by alexschrod** [comment]
Never mind, I made a boo-boo when I created the map. Sorry for the noise.

**Comment by ilyvion** [comment]
@Megadash452 It's been a while, heh. But if I recall correctly, I used different types when calculating the map and when representing the map or something like that. Once I made the two match the problem went away for me... but this is like a whisper of a memory to me at this point.
