### ISSUE TITLE
Please update Cargo.toml so that macros work with the Rust Playground

### ISSUE THREAD

**Issue by ChaiTRex** [rust-phf/rust-phf#275]
The `phf` crate is one of the crates that can be used with the Rust Playground. However, the `macros` feature is disabled there, and so [`use phf::phf_map;` and other macros do not work](https://play.rust-lang.org/?edition=2021&code=use%20phf%3A%3Aphf_map%3B). Can you please add a suitable [Playground configuration](https://github.com/integer32llc/rust-playground/issues/192#issuecomment-388589736) to `Cargo.toml` so that it can be used nicely with the Playground?

An example they give is:

>     # Cargo.toml
>     [package]
>     name = "test"
>     
>     [package.metadata.playground]
>     default-features = true
>     features = ["std", "extra-traits"]
>     all-features = false

**Comment by YoniFeng** [comment]
Was solved by #276

**Comment by JohnTitor** [comment]
Yeah, but leaving this open until making a new release.

**Comment by emilio** [comment]
Any updates on a new release? Thanks

**Comment by JohnTitor** [comment]
Sorry for the delay, published v0.11.2!
