### ISSUE TITLE
Runtime construction

### ISSUE THREAD

**Issue by james7132** [rust-phf/rust-phf#285]
The current form of the crate only allows creating PHFs at compile time. How hard would it be to allow creation of Maps at runtime?

**Comment by JohnTitor** [comment]
We had a crate for that named `phf_builder` in the past but it was removed as it'd be better to use `HashMap`: https://github.com/rust-phf/rust-phf/pull/168#issuecomment-513043200
I think this comment still makes some sense and I personally don't have a plan to revive it, sorry.
